name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Package Helm chart
        run: |
          mkdir -p helm-packages
          helm package mychart --destination helm-packages

      - name: Create index.yaml
        run: helm repo index helm-packages --url https://mobohram.github.io/test-helm-charts/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: helm-packages
          publish_branch: gh-pages
